# Generated by Django 4.1.7 on 2023-06-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuitos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=12)),
                ('descripcion', models.TextField(max_length=512)),
                ('balance_deficit', models.FloatField()),
                ('numero_de_afectaciones', models.IntegerField()),
                ('ultima_afectacion', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('afectado', models.BooleanField()),
                ('descripcion', models.TextField(max_length=512)),
                ('mw_afectados_en_provincia', models.IntegerField()),
                ('fecha', models.DateField()),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_une.circuitos')),
            ],
        ),
        migrations.CreateModel(
            name='Afectaciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora_afectacion', models.DateTimeField()),
                ('hora_restablecido', models.DateTimeField()),
                ('tiempo_de_afectacion', models.TimeField()),
                ('circuito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control_une.circuitos')),
            ],
        ),
    ]
