# Generated by Django 4.1.7 on 2023-06-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_une', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_SEN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('prevision_de_afectacion', models.IntegerField()),
                ('afectacion_real', models.IntegerField()),
                ('tiempo_afectacion', models.IntegerField()),
            ],
        ),
    ]
