# Generated by Django 4.1.7 on 2023-06-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_une', '0002_estado_sen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado_sen',
            old_name='tiempo_afectacion',
            new_name='tiempo_de_afectacion',
        ),
    ]
